namespace CSharpBasicsAssignment;

/*
 Part A: 
1-
.csproj: 
The project file itself and it has all the configs and settings for the project. It also has the target framework and packages.
Program.cs:
It is the main entry point for the app
/obj:
This has temp build files and other files that are generated by the compiler.
/bin:
This has the compiled output of the project. such as exceutables and other files required to run the project.

2-
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>

3- Added the namespace CSharpBasicsAssignment to the Program.cs file.
 A file-scoped namespace applies to the entire file without using
 curly braces. This removes one level of indentation because the
 code does not need to be nested inside a namespace block.

4- I am using the newer .slnx solution format.
 One advantage of the classic .sln format is that it is widely supported
 
 */
internal class Program
{
    private static string scopeDstring = "Hello from the outer scope!";

    private static void Main(string[] args)
    {
        RunTypeDemos();
        RunValueVsReferenceDemo();
        ScopeD();
        Console.WriteLine($"Single Number is: {FindSingleNumber(new int[] { 4, 1, 2, 1, 2 })}");
        Console.WriteLine($"Single Number is: {FindSingleNumber(new int[] { 7, 7, 2, 3, 3 })}");

    }
    /* Part B*/
    private static void RunTypeDemos()
    {
        int myInt = 11;
        Console.WriteLine($"The value of myInt is: {myInt}, Runtime Type: {myInt.GetType()}");

        long myLong = 1234567890123456789L;
        Console.WriteLine($"The value of myLong is: {myLong}, Runtime Type: {myLong.GetType()}");

        double myDouble = 3.14159;
        Console.WriteLine($"The value of myDouble is: {myDouble}, Runtime Type: {myDouble.GetType()}");

        decimal myDecimal = 19.99m;
        Console.WriteLine($"The value of myDecimal is: {myDecimal}, Runtime Type: {myDecimal.GetType()}");

        bool myBool = true;
        Console.WriteLine($"The value of myBool is: {myBool}, Runtime Type: {myBool.GetType()}");

        char myChar = 'B';
        Console.WriteLine($"The value of myChar is: {myChar}, Runtime Type: {myChar.GetType()}");

        string myString = "Hello, C#!";
        Console.WriteLine($"The value of myString is: {myString}, Runtime Type: {myString.GetType()}");

        var myVar = 11;
        Console.WriteLine($"The value of myVar is: {myVar}, Runtime Type: {myVar.GetType()}");

        int myInt2 = 1;
        long myLong2 = myInt2; // Implicit conversion from int to long

        char letter = 'B';
        int letterValue = letter; // Implicit conversion from char to int

        Console.WriteLine($"The value of myLong2 is: {myLong2}, Runtime Type: {myLong2.GetType()}");
        Console.WriteLine($"The value of letterValue is: {letterValue}, Runtime Type: {letterValue.GetType()}");

        // An int is smaller than a long, so C# can safely convert it automatically.
        // A char is represented by a Unicode numeric value, so C# can automatically convert 'B' to its numeric value (66).

        double myDouble2 = 3.75;
        int myInt3 = (int)myDouble2; // Explicit conversion from double to int
        int myInt4 = Convert.ToInt32(myDouble2); // Using Convert class to convert double to int

        Console.WriteLine($"The value of myInt3 is: {myInt3}, the value of myInt4 is: {myInt4}");

        // Casting to int will truncate the decimal part, while Convert.ToInt32 will round the value to the nearest integer.

        int myInt5 = 5 / 2;
        double myDouble3 = 5.0 / 2;
        Console.WriteLine($"The value of myInt5 is: {myInt5}, the value of myDouble3 is: {myDouble3}");
        // Integer division truncates the decimal part, while the double division retains it.

        int myInt6 = 6;
        object myObj = myInt6;
        int unboxedInt = (int)myObj; // Unboxing the object back to int
        Console.WriteLine($"The value of myObj is: {myObj}, Runtime Type: {myObj.GetType()}");
        Console.WriteLine($"The value of unboxedInt is: {unboxedInt}, Runtime Type: {unboxedInt.GetType()}");

        string myString2 = "42";
        int parsedInt = int.Parse(myString2); // Parsing string to int
        string badString = "abc";
        bool success = int.TryParse(badString, out int result);
        Console.WriteLine($"The value of parsedInt is: {parsedInt}");
        Console.WriteLine($"The value of success is: {success}, the value of result is: {result}");

        float myFloat = 3.14f;
        decimal myDecimal2 = (decimal)myFloat; // Explicit conversion from float to decimal
        Console.WriteLine($"The value of myDecimal2 is: {myDecimal2}, Runtime Type: {myDecimal2.GetType()}");

        //decimal decimalValue = floatValue;
        // Compiler will refuse to implicitly convert float to decimal because it can lead to loss of precision. You need to explicitly cast it.

    }

    /* Part C */
    struct Point
    {
        public int X;
        public int Y;
    }

    private static void RunValueVsReferenceDemo()
    {
        // Experiment #1: Value Type (Struct) Assignment
        Point p1 = new Point { X = 1, Y = 2 };
        Point p2 = p1; // Value type assignment, creates a copy
        p2.X = 99;

        // Changing p2 does not affect p1 because structs are value types
        // and assigning one struct to another creates an independent copy.
        Console.WriteLine($"p1.X: {p1.X}, p2.X: {p2.X}");


        // Experiment #2: Reference Type (Class) Assignment
        Order o1 = new Order
        {
            OrderId = 101,
            CustomerName = "Basma",
            Quantity = 3,
            UnitPrice = 100m,
            TotalPrice = 0m,
            IsPaid = false,
            DiscountPercent = 10.0,
            ShippingCity = "Cairo",
            Priority = 'H',
            ItemCode = 123456789L
        };

        o1.CalculateTotal();

        Order o2 = o1;
        o2.IsPaid = true;
        Console.WriteLine($"o1.IsPaid: {o1.IsPaid}, o2.IsPaid: {o2.IsPaid}");
        // Reference type assignment, both o1 and o2 refer to the same object SO CHANGING o2 WILL CHANGE o1

        object boxedOrder = o1; // Boxing the reference type
        Order o3 = (Order)boxedOrder;

        Console.WriteLine($"o1.IsPaid: {o1.IsPaid}, o3.IsPaid: {o3.IsPaid}");

        o2.PrintSummary();

    }

    /* Part D */
    private static void ScopeD()
    {
        /* D1 */
        string innerScopeDstring = "Hello from the inner scope!";
        Console.WriteLine(scopeDstring); // Accessing the outer scope variable

        for (int i = 0; i < 10; i++)
        {
            int loopVariable = i * 2;
            Console.WriteLine($"Loop iteration {i}: loopVariable = {loopVariable}");

        }
        // The loopVariable is not accessible here because it's out of scope
        // Console.WriteLine(loopVariable,i);

        /* D2 */
        int total = 100;
        total += 10; // 100 + 10
        Console.WriteLine($"Total: {total}");

        total -= 20; // 110 - 20
        Console.WriteLine($"Total: {total}");

        total *= 2; // 90 * 2
        Console.WriteLine($"Total: {total}");

        total /= 2; // 180 / 2
        Console.WriteLine($"Total: {total}");

        total %= 2; // 90 % 2
        Console.WriteLine($"Total: {total}");

        /* D3 */
        int a = 12;
        int b = 10;
        Console.WriteLine($"a & b: {a & b}");
        Console.WriteLine($"a | b: {a | b}");
        Console.WriteLine($"a ^ b: {a ^ b}");

        /* 
        a & b: 8
        a | b: 14
        a ^ b: 6
        */

        // & evaluates both operands even if the left operand is false,
        // while && short-circuits and does not evaluate the right operand when the left operand is false.

    }

    /* Part F */
    // Solve LeetCode 136 — Single Number:
    // Example
    //Input: nums = [4, 1, 2, 1, 2]
    //Output: 4
    private static int FindSingleNumber(int[] nums)
    {
        int result = 0;

        for (int i = 0; i < nums.Length; i++)
        {
            result ^= nums[i]; // XOR operation
        }
        return result;
    }
}


